# Generated by Django 4.2.2 on 2023-07-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_category_category_n_product_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
